### ISSUE TITLE
Air Temperature is Air Temperature at 2 metres

### ISSUE THREAD

**Issue by annefou** [Quickbeasts51429/Outreachy_Galaxy_Community_contributor#1]
Awesome! 👏 

Bear in mind that Air Temperature is Air Temperature at 2 metres (near surface temperature). This is an important information for readers/visitors.

**Comment by Quickbeasts51429** [comment]
I will change the insights accordingly....I kind of just went with the
flow...thanks a lot for correcting.

**Comment by j34ni** [comment]
Nice website, I really like the layout
I agree with @annefou that it is very important to be precise on the variables used (here 2m air temperature) since air temperature could be at any height in the atmosphere (and obviously it varies a lot vertically). Do not forget to correct this in all the pages. I would also add everywhere the source of the data (in this instance ECMWF ERA5), since it matters a lot where the values come from and how trustworthy they are.

**Comment by Quickbeasts51429** [comment]
Thank a lot..I will change those headings accordingly by tonight..

**Comment by Quickbeasts51429** [comment]
Thanks*

**Comment by Quickbeasts51429** [comment]
I've made the changes for this issue. Kindly look into it once. Then would close the issue.

**Comment by annefou** [comment]
Nice. Did you mention the source of the data (ECMWF ERA5)?

**Comment by Quickbeasts51429** [comment]
Oh..yes I haven't done that!...Noted!

**Comment by Quickbeasts51429** [comment]
I've made the changes for this issue. Please review once.

**Comment by annefou** [comment]
Excellent! Let's close this issue.
