### ISSUE TITLE
Mahua

### ISSUE THREAD

**Issue by annefou** [Quickbeasts51429/Outreachy_Galaxy_Community_contributor#5]
So cool. I did not know about this wine. If you have links about it you can add so we can learn more about it.

The region where Mahua trees grow can be relevant too. Can we see from the map if we are in the "right" range? Maybe you could say something about it; like on that day everything is fine (or not!).
I guess the time you display are in UTC (it would be worth adding UTC and local time too).
Do you know if people have had issues with the production because of climate change?

**Comment by j34ni** [comment]
Knowing that care could have been be taken at particular times of a particular day **in the past** is not much use since it is too late to react. What could potentially be more interesting for farmers could be to know the trend and relate it to other local changes (is this more frequent since the expansion of the production zone?), or in which areas this phenomenon occurs most (so that they can start thinking about growing something else) or where it is less pronounced (if it was possible to "move" their production there).

Of course, this is not directly related to Q5 but more to Q7 and how we could think about this case from a more "climate oriented" point of view (i.e., in the longer term).

**Comment by Quickbeasts51429** [comment]
That would be truly interesting to research upon...would be updating shortly as soon as I come up with something more significant..
 Thanks!

> Knowing that care could have been be taken at particular times of a particular day **in the past** is not much use since it is too late to react. What could potentially be more interesting for farmers could be to know the trend and relate it to other local changes (is this more frequent since the expansion of the production zone?), or in which areas this phenomenon occurs most (so that they can start thinking about growing something else) or where it is less pronounced (if it was possible to "move" their production there).
> 
> Of course, this is not directly related to Q5 but more to Q7 and how we could think about this case from a more "climate oriented" point of view (i.e., in the longer term).

**Comment by annefou** [comment]
Very good. I see that you have added local times. Thank you. well done.👍

**Comment by Quickbeasts51429** [comment]
For this issue, I'll be adding the information related to climate conditions necessary for Growth of "Mahua Tree". I'll also be mentioning temperatures related problems faced by this liquor industry. 
I've got some new ideas about " Cashew Nut Plantation" in my state...I'll write something relevant o that. Also I'll be writing about min and max temperatures required for zaid crops grown here

**Comment by annefou** [comment]
That's really great! You do a lot of work to find really very interesting local aspect of the climate in this region.

**Comment by Quickbeasts51429** [comment]
Thanks a lot...really excited to show you my findings!!
